inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  
AllCops:
  NewCops: enable
  Exclude:
    - 'config/environments/production.rb'
    - 'bin/*'

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false  

Style/FrozenStringLiteralComment:
  Enabled: false